platform :ios, '7.0'

# GameAbstract
pod 'MSKit', :git=>'git@github.com:e7mac/MSKit'
pod 'TPServiceFramework', :git=>'git@github.com:tidepool/TPServiceFramework'
pod 'TPGameFramework', :git=>'git@github.com:tidepool/TPGameFramework'
pod 'CrashlyticsFramework', '~> 2.2.0'

pod 'TP{{Project}}', :path=>'../TP{{Project}}.podspec'

target 'TP{{Project}}Tests', :exclusive => true do
  pod 'Kiwi/XCTest'
end